version: '3.7'

services:
  web:
    build:
        context: ./core/web
        dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./core/nginx
    ports:
    - 1337:80
    depends_on:
      - web

volumes:
  pg_data: